-- Garage 1319 V2: esquema auditable, RLS y operaciones transaccionales.
-- Ejecutar primero en un proyecto de prueba. No borra tablas ni datos existentes.
create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  precio numeric(12,2) not null check (precio >= 0),
  precio_promocional numeric(12,2) check (precio_promocional is null or (precio_promocional >= 0 and precio_promocional < precio)),
  stock integer not null default 0 check (stock >= 0),
  estado text not null default 'disponible' check (estado in ('disponible','reservado','vendido')),
  visible boolean not null default true,
  categoria text not null default 'Básico',
  coleccion text not null default '',
  descripcion text not null default '',
  imagen text not null default '',
  imagen_posterior text not null default '',
  escala text not null default '',
  condicion_empaque text not null default '',
  tipo_edicion text not null default '',
  entrega text not null default '',
  caracteristicas text[] not null default '{}',
  orden integer not null default 0,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.configuracion (
  clave text primary key,
  valor text not null default '',
  actualizado_en timestamptz not null default now()
);

create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  telefono text not null unique,
  email text not null default '',
  direccion text not null default '',
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  cliente_id bigint references public.clientes(id),
  cliente_nombre text not null,
  telefono text not null,
  email text not null default '',
  direccion text not null default '',
  notas text not null default '',
  estado text not null default 'pendiente' check (estado in ('pendiente','confirmado','vendido','cancelado')),
  total numeric(12,2) not null default 0 check (total >= 0),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  vendido_en timestamptz
);

create table if not exists public.pedido_items (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  producto_id bigint not null references public.productos(id),
  producto_nombre text not null,
  codigo text not null,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(12,2) not null check (precio_unitario >= 0),
  subtotal numeric(12,2) not null check (subtotal >= 0)
);

create table if not exists public.reservas (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references public.productos(id),
  cliente text not null,
  telefono text not null default '',
  estado text not null default 'Activa',
  vence_en timestamptz not null,
  creado_en timestamptz not null default now()
);

create table if not exists public.promociones (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references public.productos(id) on delete cascade,
  titulo text not null default 'OFERTA',
  tipo text not null default 'percent' check (tipo in ('percent','price')),
  valor numeric(12,2) not null check (valor >= 0),
  descuento numeric(12,2) not null default 0,
  activa boolean not null default true,
  fin timestamptz,
  creado_en timestamptz not null default now()
);

create table if not exists public.historial (
  id bigint generated by default as identity primary key,
  usuario_id uuid references auth.users(id),
  accion text not null,
  detalle text not null default '',
  creado_en timestamptz not null default now()
);

create or replace function public.is_garage_admin()
returns boolean language sql stable security definer set search_path=public,pg_temp as $$
  select exists(select 1 from public.admin_users where user_id=auth.uid());
$$;

alter table public.admin_users enable row level security;
alter table public.productos enable row level security;
alter table public.configuracion enable row level security;
alter table public.clientes enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedido_items enable row level security;
alter table public.reservas enable row level security;
alter table public.promociones enable row level security;
alter table public.historial enable row level security;

drop policy if exists "admin users self read" on public.admin_users;
create policy "admin users self read" on public.admin_users for select to authenticated using (user_id=auth.uid());
drop policy if exists "public visible products" on public.productos;
create policy "public visible products" on public.productos for select to anon,authenticated using (visible=true and stock>0 or public.is_garage_admin());
drop policy if exists "admin manages products" on public.productos;
create policy "admin manages products" on public.productos for all to authenticated using (public.is_garage_admin()) with check (public.is_garage_admin());
drop policy if exists "public business config" on public.configuracion;
create policy "public business config" on public.configuracion for select to anon,authenticated using (clave in ('brand_name','brand_subtitle','brand_whatsapp','brand_currency','brand_primary','brand_bg','brand_logo','negocio_nombre','negocio_subtitulo','negocio_moneda','negocio_instagram','negocio_entrega','whatsapp') or public.is_garage_admin());
drop policy if exists "admin manages config" on public.configuracion;
create policy "admin manages config" on public.configuracion for all to authenticated using (public.is_garage_admin()) with check (public.is_garage_admin());
drop policy if exists "public active promos" on public.promociones;
create policy "public active promos" on public.promociones for select to anon,authenticated using ((activa=true and (fin is null or fin>now())) or public.is_garage_admin());
drop policy if exists "admin manages promos" on public.promociones;
create policy "admin manages promos" on public.promociones for all to authenticated using (public.is_garage_admin()) with check (public.is_garage_admin());

do $$ declare t text; begin
  foreach t in array array['clientes','pedidos','pedido_items','reservas','historial'] loop
    execute format('drop policy if exists %I on public.%I','admin manages '||t,t);
    execute format('create policy %I on public.%I for all to authenticated using (public.is_garage_admin()) with check (public.is_garage_admin())','admin manages '||t,t);
  end loop;
end $$;

create or replace function public.crear_pedido(p_cliente jsonb,p_items jsonb,p_notas text default '')
returns table(codigo text,total numeric,pedido_id bigint)
language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_cliente_id bigint; v_pedido_id bigint; v_codigo text; v_total numeric(12,2):=0;
  v_item jsonb; v_producto public.productos%rowtype; v_cantidad integer; v_subtotal numeric(12,2); v_precio numeric(12,2);
  v_nombre text:=trim(coalesce(p_cliente->>'nombre','')); v_telefono text:=regexp_replace(coalesce(p_cliente->>'telefono',''),'\D','','g');
  v_email text:=trim(coalesce(p_cliente->>'email','')); v_direccion text:=trim(coalesce(p_cliente->>'direccion',''));
begin
  if length(v_nombre)<2 then raise exception 'Nombre inválido'; end if;
  if length(v_telefono)<9 or length(v_telefono)>15 then raise exception 'Teléfono inválido'; end if;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'El pedido no contiene productos'; end if;
  if jsonb_array_length(p_items)>30 then raise exception 'El pedido supera el máximo de productos'; end if;

  insert into public.clientes(nombre,telefono,email,direccion)
  values(v_nombre,v_telefono,v_email,v_direccion)
  on conflict(telefono) do update set nombre=excluded.nombre,email=excluded.email,direccion=excluded.direccion,actualizado_en=now()
  returning id into v_cliente_id;

  v_codigo:='G1319-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));
  insert into public.pedidos(codigo,cliente_id,cliente_nombre,telefono,email,direccion,notas,estado,total)
  values(v_codigo,v_cliente_id,v_nombre,v_telefono,v_email,v_direccion,left(coalesce(p_notas,''),500),'pendiente',0)
  returning id into v_pedido_id;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_cantidad:=greatest(0,coalesce((v_item->>'cantidad')::integer,0));
    if v_cantidad<1 or v_cantidad>20 then raise exception 'Cantidad inválida'; end if;
    select * into v_producto from public.productos where id=(v_item->>'producto_id')::bigint and visible=true for update;
    if not found then raise exception 'Producto no disponible'; end if;
    if v_producto.stock<v_cantidad then raise exception 'Stock insuficiente para %',v_producto.nombre; end if;
    v_precio:=coalesce(v_producto.precio_promocional,v_producto.precio);
    select case when p.tipo='percent' then greatest(0,round(v_producto.precio*(1-p.valor/100),2)) else p.valor end
      into v_precio from public.promociones p
      where p.producto_id=v_producto.id and p.activa=true and (p.fin is null or p.fin>now())
      order by p.id desc limit 1;
    v_precio:=coalesce(v_precio,v_producto.precio_promocional,v_producto.precio);
    v_subtotal:=v_precio*v_cantidad; v_total:=v_total+v_subtotal;
    insert into public.pedido_items(pedido_id,producto_id,producto_nombre,codigo,cantidad,precio_unitario,subtotal)
    values(v_pedido_id,v_producto.id,v_producto.nombre,v_producto.codigo,v_cantidad,v_precio,v_subtotal);
    update public.productos set stock=stock-v_cantidad,estado=case when stock-v_cantidad<=0 then 'vendido' else 'disponible' end,visible=(stock-v_cantidad>0),actualizado_en=now() where id=v_producto.id;
  end loop;
  update public.pedidos set total=v_total where id=v_pedido_id;
  insert into public.historial(accion,detalle) values('Pedido creado',v_codigo);
  return query select v_codigo,v_total,v_pedido_id;
end $$;

create or replace function public.confirmar_pedido_venta(p_pedido_id bigint)
returns boolean language plpgsql security definer set search_path=public,pg_temp as $$
declare v_order public.pedidos%rowtype;
begin
  if not public.is_garage_admin() then raise exception 'Acceso denegado'; end if;
  select * into v_order from public.pedidos where id=p_pedido_id for update;
  if not found then raise exception 'Pedido no encontrado'; end if;
  if v_order.estado='cancelado' then raise exception 'El pedido está cancelado'; end if;
  if v_order.estado='vendido' then return true; end if;
  update public.pedidos set estado='vendido',vendido_en=now(),actualizado_en=now() where id=p_pedido_id;
  insert into public.historial(usuario_id,accion,detalle) values(auth.uid(),'Venta confirmada',v_order.codigo);
  return true;
end $$;

create or replace function public.cancelar_pedido(p_pedido_id bigint)
returns boolean language plpgsql security definer set search_path=public,pg_temp as $$
declare v_order public.pedidos%rowtype; v_item public.pedido_items%rowtype;
begin
  if not public.is_garage_admin() then raise exception 'Acceso denegado'; end if;
  select * into v_order from public.pedidos where id=p_pedido_id for update;
  if not found then raise exception 'Pedido no encontrado'; end if;
  if v_order.estado='cancelado' then return true; end if;
  if v_order.estado='vendido' then raise exception 'No se puede cancelar una venta confirmada'; end if;
  for v_item in select * from public.pedido_items where pedido_id=p_pedido_id loop
    update public.productos set stock=stock+v_item.cantidad,estado='disponible',visible=true,actualizado_en=now() where id=v_item.producto_id;
  end loop;
  update public.pedidos set estado='cancelado',actualizado_en=now() where id=p_pedido_id;
  insert into public.historial(usuario_id,accion,detalle) values(auth.uid(),'Pedido cancelado',v_order.codigo);
  return true;
end $$;

revoke all on function public.crear_pedido(jsonb,jsonb,text) from public;
grant execute on function public.crear_pedido(jsonb,jsonb,text) to anon,authenticated;
revoke all on function public.confirmar_pedido_venta(bigint) from public;
grant execute on function public.confirmar_pedido_venta(bigint) to authenticated;
revoke all on function public.cancelar_pedido(bigint) from public;
grant execute on function public.cancelar_pedido(bigint) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('product-images','product-images',true,12582912,array['image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "public reads product images" on storage.objects;
create policy "public reads product images" on storage.objects for select to public using (bucket_id='product-images');
drop policy if exists "admins upload product images" on storage.objects;
create policy "admins upload product images" on storage.objects for insert to authenticated with check (bucket_id='product-images' and public.is_garage_admin());
drop policy if exists "admins manage product images" on storage.objects;
create policy "admins manage product images" on storage.objects for all to authenticated using (bucket_id='product-images' and public.is_garage_admin()) with check (bucket_id='product-images' and public.is_garage_admin());

-- PASO MANUAL ÚNICO: después de crear/invitar el usuario en Supabase Auth, autorízalo:
-- insert into public.admin_users(user_id) values ('UUID-DEL-USUARIO') on conflict do nothing;
