-- Embudo comercial anónimo y sin datos personales para Garage 1319.
create table if not exists public.eventos_analitica (
  id bigint generated by default as identity primary key,
  evento text not null check (evento in (
    'visita',
    'detalle_producto',
    'clic_whatsapp',
    'agregar_carrito',
    'compartir_producto',
    'pedido_registrado'
  )),
  producto_id bigint references public.productos(id) on delete set null,
  codigo_producto text check (codigo_producto is null or char_length(codigo_producto) <= 80),
  sesion_id text not null check (char_length(sesion_id) between 8 and 120),
  pagina text check (pagina is null or char_length(pagina) <= 300),
  referencia text check (referencia is null or char_length(referencia) <= 500),
  datos jsonb not null default '{}'::jsonb,
  creado_en timestamptz not null default now()
);

create index if not exists eventos_analitica_creado_en_idx
  on public.eventos_analitica (creado_en desc);
create index if not exists eventos_analitica_evento_creado_en_idx
  on public.eventos_analitica (evento, creado_en desc);
create index if not exists eventos_analitica_codigo_producto_idx
  on public.eventos_analitica (codigo_producto)
  where codigo_producto is not null;
create index if not exists eventos_analitica_producto_id_idx
  on public.eventos_analitica (producto_id)
  where producto_id is not null;

alter table public.eventos_analitica enable row level security;

revoke all on table public.eventos_analitica from anon, authenticated;
grant insert on table public.eventos_analitica to anon, authenticated;
grant select on table public.eventos_analitica to authenticated;
grant usage, select on sequence public.eventos_analitica_id_seq to anon, authenticated;

drop policy if exists "Registrar eventos públicos" on public.eventos_analitica;
create policy "Registrar eventos públicos"
on public.eventos_analitica
for insert
to anon, authenticated
with check (
  evento in ('visita','detalle_producto','clic_whatsapp','agregar_carrito','compartir_producto','pedido_registrado')
  and char_length(sesion_id) between 8 and 120
  and jsonb_typeof(datos) = 'object'
  and pg_column_size(datos) <= 4096
);

drop policy if exists "Administración consulta analítica" on public.eventos_analitica;
create policy "Administración consulta analítica"
on public.eventos_analitica
for select
to authenticated
using (true);

comment on table public.eventos_analitica is
  'Eventos agregados del embudo comercial; no almacena nombre, teléfono, correo ni dirección.';
